### ISSUE TITLE
MA57 vs MA97

### ISSUE THREAD

**Issue by lrsantos11** [JuliaSmoothOptimizers/HSL.jl#12]
@dpo Do you think is worth to implement a wrapper for HSL_MA57? What is the biggest difference? I'm not sure which one should I use.
BTW, are you going to ISMP at Bordeaux? If so, we should drink some wine and talk (live).
Cheers,

Rafa

**Comment by dpo** [comment]
There is one in the `ma57` branch already. I haven't merged it because it requires some extra code that I might not be allowed to post online. Yes, I'll be at ISMP. Looking forward to seeing you there!

**Comment by lrsantos11** [comment]
I'm trying to install form the MA57 branch however that's the error I got
```julia
INFO: Building HSL
INFO: looking for /Users/lrsantos/.julia/v0.6/HSL/deps/downloads/hsl_ma57-5.2.0.tar.gz
INFO: hsl_ma57 found
INFO: looking for /Users/lrsantos/.julia/v0.6/HSL/deps/downloads/hsl_ma97-2.4.0.tar.gz
INFO: hsl_ma97 found
Info: Attempting to create directory /Users/lrsantos/.julia/v0.6/HSL/deps/src
Info: Directory /Users/lrsantos/.julia/v0.6/HSL/deps/src already exists
Info: Attempting to create directory /Users/lrsantos/.julia/v0.6/HSL/deps
Info: Directory /Users/lrsantos/.julia/v0.6/HSL/deps already exists
Info: Path /Users/lrsantos/.julia/v0.6/HSL/deps/src/hsl_ma57-5.2.0 already exists
Info: Changing directory to /Users/lrsantos/.julia/v0.6/HSL/deps/src/hsl_ma57-5.2.0
==================================================================================[ ERROR: HSL ]==================================================================================

LoadError: ReadOnlyMemoryError()
while loading /Users/lrsantos/.julia/v0.6/HSL/deps/build.jl, in expression starting on line 48

==================================================================================================================================================================================

=================================================================================[ BUILD ERRORS ]=================================================================================

WARNING: HSL had build errors.

 - packages with build errors remain installed in /Users/lrsantos/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("HSL")`
 - build a single package by running its `deps/build.jl` script

```
Any insight would be welcome. Btw, this error occurred when I tried to reinstall MA97 library after I GCC 8 was the main compiler on Homebrew. Is this the case?

**Comment by lrsantos11** [comment]
Seems like it's working. I tried now the manual installation and this is the gist:
https://gist.github.com/lrsantos11/9442a02338970b792bd23b3903794cac

I'll correct those those warnings and I'll made the PR. 

Anyway, the automatic installation is not working. 

I don't know why.

**Comment by dpo** [comment]
I've had this error before. I think Homebrew.jl was the source of the issue. Try purging it completely (`rm -rf ~/.julia/v0.6/Homebrew.jl`) and starting over.

**Comment by lrsantos11** [comment]
It worked. Thanks!
Em ter, 12 de jun de 2018 às 11:52, Dominique <notifications@github.com>
escreveu:
