### ISSUE TITLE
HSL Ma97 and Ma57 functions do not export when `using HSL`

### ISSUE THREAD

**Issue by zornsllama** [JuliaSmoothOptimizers/HSL.jl#173]
Hi,

I have followed the installation instructions for HSL.jl, namely to set the "HSL_ARCHIVES_PATH" environment variable to the directory where I unzipped the coinhsl.zip archive, and then to build using Pkg. However, the installation does not seem to work, as the Ma97 and Ma57 symbols are not exported. I also tried setting the environment variables "HSL_MA57_PATH" and "HSL_MA97_PATH" to the directory, which unfortunately didn't work either. Any help would be greatly appreciated!

Thanks!

**Edit:** After pointing "HSL_ARCHIVES_PATH" to a folder with the uncompressed coinhsl.zip, it seems that the build process has compiled libcoinhsl.so, and "HSL.available_hsl_algorithms" contains the key-value pair "coinhsl" => v"2021.5.5"  . However, this still does not expose Ma57 or Ma97, and it's not clear to me how I can interact with the solvers.

**Comment by amontoison** [comment]
Hi @zornsllama, you need to keep the archive zipped 
. Can you try again?

**Comment by zornsllama** [comment]
@amontoison thanks for your reply! Sorry, I had a typo in my edit to the post -- it should have read "compressed coinhsl.zip," i.e. I did try this again with the archive zipped. This seems to have resulted in compilation of libcoinhsl.so, but the Ma57 and Ma97 functions are still unavailable.

**Comment by amontoison** [comment]
@zornsllama Does it solve your problem?

**Comment by zornsllama** [comment]
Thanks! Yes, this works. Good to hear there will also eventually be a JuliaHSL package.

**Comment by amontoison** [comment]
@zornsllama 
For information, we released [JuliaHSL](https://licences.stfc.ac.uk/product/julia-hsl).
