### ISSUE TITLE
Warning + error while adding package

### ISSUE THREAD

**Issue by jbcaillau** [JuliaSmoothOptimizers/HSL.jl#210]
@amontoison aware of this? installing some packages (`DifferentialEquations.jl`, to name it) while `HSL.jl` is already present.
![IMG_3312](https://github.com/JuliaSmoothOptimizers/HSL.jl/assets/62183989/58974052-cfcb-4034-8749-9e8419d6f0ef)

**Comment by amontoison** [comment]
@jbcaillau It's related to `Revise.jl` and not `HSL.jl` or `DifferentialEquations.jl`.

**Comment by jbcaillau** [comment]
✅ thanks @amontoison

**Comment by amontoison** [comment]
I suggest to open the same issue in the repository of `Revise.jl`.
