### ISSUE TITLE
Prepackaged RPM dependencies on Windows

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/HSL.jl#3]
- [ ] BLAS
- [ ] LAPACK
- [ ] METIS 4

**Comment by tkelman** [comment]
https://build.opensuse.org/package/show/windows:mingw:win64/mingw64-metis

**Comment by dpo** [comment]
That's METIS 5.

**Comment by tkelman** [comment]
Can't HSL use Metis 5? The license is much more reasonable on that, and so's the build system.

**Comment by dpo** [comment]
At least HSL_MA97 is METIS 4 only. I'll have to check the others, but my guess is few, if any, will support METIS 5.

**Comment by tkelman** [comment]
Oh, that's too bad. Worth pinging Jonathan Hogg to ask if there's any ETA on Metis-5-compatible versions?

**Comment by dpo** [comment]
I've already been harassing him about building shared libs and that might be under way. But I'll ask.

**Comment by dpo** [comment]
Solved by way of OpenBLASBuider and CoinMETISBuilder.
