### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/HSL.jl#31]
Checklist
- [x] Merge `ma57` into `master` (#33)
- [x] Project.toml (#23, #32)

**Comment by dpo** [comment]
That would be fine, but `get_factors` and `alter_d` are only defined if the user has the MA57 patch. So we should check that those symbols exist in the shared library before defining the Julia functions.

**Comment by abelsiqueira** [comment]
If the user doesn't have the patch, it doesn't even build, I think.

**Comment by abelsiqueira** [comment]
@JuliaRegistrator register()

**Comment by dpo** [comment]
Pretty amazing!!!

**Comment by lrsantos11** [comment]
Yeah. Great work guys.
