### ISSUE TITLE
Build error in Julia 1.0.5

### ISSUE THREAD

**Issue by david-m-rosen** [JuliaSmoothOptimizers/HSL.jl#39]
Hey all,

First, let me say thanks for putting this package together -- this looks like it's going to be really helpful :-)

When trying to build this package with HSL_MA57, following the instructions in the README, I encounter the following error (taken from the logfile):

> Making install in example
> make[1]: Entering directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0/example'
> make[2]: Entering directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0/example'
> make[2]: Nothing to be done for 'install-exec-am'.
> make[2]: Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0/example'
> make[1]: Leaving directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0/example'
> make[1]: Entering directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0'
> make[2]: Entering directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0'
> make[2]: Nothing to be done for 'install-exec-am'.
> make[2]: Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0'
> make[1]: Leaving directory '/home/dmrosen/.julia/dev/HSL/deps/usr/src/hsl_ma57-5.2.0'
> /usr/bin/ld: /home/dmrosen/.julia/dev/HSL/deps/usr/lib/libhsl_ma57.a(hsl_ma57s.o): relocation R_X86_64_PC32 against symbol `__hsl_ma57_single_MOD_ma57_regen' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> [ Info: building ma57
> ERROR: LoadError: LoadError: failed process: Process(`gfortran -fPIC -shared -Wl,--whole-archive /home/dmrosen/.julia/dev/HSL/deps/usr/lib/libhsl_ma57.a -L/home/dmrosen/.julia/dev/HSL/deps/usr/lib -lopenblas -lcoinmetis -lgomp -Wl,--no-whole-archive -o /home/dmrosen/.julia/dev/HSL/deps/usr/lib/libhsl_ma57.so`, ProcessExited(1)) [1]
> Stacktrace:
>  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
>  [2] pipeline_error at ./process.jl:705 [inlined]
>  [3] #run#505(::Bool, ::Function, ::Cmd) at ./process.jl:663
>  [4] run(::Cmd) at ./process.jl:661
>  [5] top-level scope at none:0
>  [6] include at ./boot.jl:317 [inlined]
>  [7] include_relative(::Module, ::String) at ./loading.jl:1044
>  [8] include(::Module, ::String) at ./sysimg.jl:29
>  [9] include(::String) at ./client.jl:392
>  [10] top-level scope at /home/dmrosen/.julia/dev/HSL/deps/build.jl:78
>  [11] include at ./boot.jl:317 [inlined]
>  [12] include_relative(::Module, ::String) at ./loading.jl:1044
>  [13] include(::Module, ::String) at ./sysimg.jl:29
>  [14] include(::String) at ./client.jl:392
>  [15] top-level scope at none:0
> in expression starting at /home/dmrosen/.julia/dev/HSL/deps/build_hsl_ma57.jl:15
> in expression starting at /home/dmrosen/.julia/dev/HSL/deps/build.jl:22 

It looks here like the operative lines are:

>  /usr/bin/ld: /home/dmrosen/.julia/dev/HSL/deps/usr/lib/libhsl_ma57.a(hsl_ma57s.o): relocation R_X86_64_PC32 against symbol `__hsl_ma57_single_MOD_ma57_regen' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status

Any idea what might be causing this error?  (I'm running Julia 1.0.5 on Ubuntu 18.04, using the Julia editor in Atom)  

Any help would be greatly appreciated!

**Comment by dpo** [comment]
Thanks for the report. It's unfortunate I can't use CI on this repository.

Do you know what version of gfortran Julia is using in your build?

If you know how, could you try building MA57 by hand using the `configure` command [here](https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/master/deps/build_hsl_ma57.jl#L13) and then say `make` to see if it succeeds? You can probably leave out the options related to BLAS and METIS in this experiment.

**Comment by david-m-rosen** [comment]
Hi Dominique,

Thanks for the quick reply :-)!

Here's what I get from `gfortran --version`:

> GNU Fortran (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
> Copyright (C) 2017 Free Software Foundation, Inc.

If I try running `./configure` as indicated (leaving out flags related to BLAS and METIS), here's what I get:

> dmrosen@wintermute:~/hsl_ma57-5.2.0$ ./configure F77=gfortran CFLAGS=-fPIC FFLAGS="-fPIC -fopenmp" FCFLAGS="-fPIC -fopenmp"
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether the Fortran 77 compiler works... yes
> checking for Fortran 77 compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU Fortran 77 compiler... yes
> checking whether gfortran accepts -g... yes
> checking for gfortran... gfortran
> checking whether we are using the GNU Fortran compiler... yes
> checking whether gfortran accepts -g... yes
> checking for gcc... gcc
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc... none
> checking for ranlib... ranlib
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking how to get verbose linking output from gfortran... -v
> checking for Fortran libraries of gfortran...  -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lgfortran -lm -lgomp -lquadmath -lpthread
> checking fortran 90 modules inclusion flag... not found
> checking how to get verbose linking output from gfortran... -v
> checking for Fortran 77 libraries of gfortran...  -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lgfortran -lm -lgomp -lquadmath -lpthread
> checking for dummy main to link with Fortran 77 libraries... none
> checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
> checking for sgemm_... no
> checking for ATL_xerbla in -latlas... no
> checking for sgemm_ in -lblas... yes
> checking for dgemm_ in -ldgemm... no
> checking for sgemm_ in -lcxml... no
> checking for sgemm_ in -ldxml... no
> checking for sgemm_ in -lscs... no
> checking for sgemm_ in -lcomplib.sgimath... no
> checking for sgemm_ in -lblas... (cached) yes
> checking for sgemm_ in -lessl... no
> checking for sgemm_ in -lblas... (cached) yes
> checking for METIS library... checking for metis_nodend_ in -L -lmetis... no
> checking for metis_nodend_ in -lmetis... no
> ./configure: line 6180: hsl_metis_ok: command not found
> configure: WARNING: No MeTiS library found. make check will not work.
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/Makefile
> config.status: creating example/Makefile
> config.status: executing depfiles commands

and then `make`:

> dmrosen@wintermute:~/hsl_ma57-5.2.0$ make
> Making all in src
> make[1]: Entering directory '/home/dmrosen/hsl_ma57-5.2.0/src'
> gfortran  -fPIC -fopenmp -c -o sdeps90.o sdeps90.f90
> gfortran  -fPIC -fopenmp -c -o hsl_ma57s.o hsl_ma57s.f90
> gfortran  -fPIC -fopenmp -c -o ddeps90.o ddeps90.f90
> gfortran  -fPIC -fopenmp -c -o hsl_ma57d.o hsl_ma57d.f90
> gfortran  -fPIC -fopenmp -c -o sdeps.o sdeps.f
> gfortran  -fPIC -fopenmp -c -o ddeps.o ddeps.f
> rm -f libhsl_ma57.a
> ar cru libhsl_ma57.a hsl_ma57s.o hsl_ma57d.o sdeps.o sdeps90.o ddeps.o ddeps90.o 
> ar: `u' modifier ignored since `D' is the default (see `U')
> ranlib libhsl_ma57.a
> gfortran  -fPIC -fopenmp -c -o fakemetis.o fakemetis.f
> rm -f libfakemetis.a
> ar cru libfakemetis.a fakemetis.o 
> ar: `u' modifier ignored since `D' is the default (see `U')
> ranlib libfakemetis.a
> make[1]: Leaving directory '/home/dmrosen/hsl_ma57-5.2.0/src'
> Making all in example
> make[1]: Entering directory '/home/dmrosen/hsl_ma57-5.2.0/example'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/dmrosen/hsl_ma57-5.2.0/example'
> make[1]: Entering directory '/home/dmrosen/hsl_ma57-5.2.0'
> make[1]: Nothing to be done for 'all-am'.
> make[1]: Leaving directory '/home/dmrosen/hsl_ma57-5.2.0'

This all looks OK to me (as far as I can tell ...)

**Comment by dpo** [comment]
Closing because the build system has changed significantly. Please open a new issue if there are still difficulties.
