### ISSUE TITLE
Allow to specify HSL archive path at installation

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/HSL.jl#54]
The current installation steps require the user to copy the HSL archive to the package's directory, before running `build HSL`.
Unless the package is dev-ed, this will typically be somewhere like `~/.julia/packages/HSL/XYZ`, possibly changing at every new version.

Commercial optimization solvers' wrappers like Gurobi.jl require the user to, instead, specify the location of their Gurobi path before before the Julia wrapper.
In the HSL case (assuming I saved the archives to `~/hsl/`, this could look like
```julia
ENV["HSL_MA57_PATH"] = "~/hsl/hsl_ma57-5.2.0.tar.gz"
ENV["HSL_MA97_PATH"] = "~/hsl/hsl_ma97-2.6.0.tar.gz"
Pkg.build("HSL")
```
From a user perspective it would remove the need to find the current package location, and manually copy the archive there.

As far as the build script is concerned, one could check whether these environment variables are defined (and, if not, look for a default location), then copy the archive to the `deps/download` and build the package as usual.

cc @amontoison

**Comment by amontoison** [comment]
I was already working on it. #55 seems to be a good solution for this issue.
