### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Goysa2** [JuliaSmoothOptimizers/HSL.jl#9]
Hi

When I try to build HSL I have the following error: 
`LoadError: Checksum mismatch!  Expected:`
`e3133eba520abcabaf1700106f8a1310d4286c61721f707e94fb7d45a220abf2`
`Calculated:`
`552114617bddbc722ef014856463d0d29c2398abda60a05debccb7a6e8e1db7a`
`Delete /home/.../.julia/v0.5/HSL/deps/downloads/hsl_ma97-2.3.0.tar.gz and try again`
`while loading /home/.../.julia/v0.5/HSL/deps/build.jl, in expression starting on line 36`

I have deleted it and tried again and it didn't work. Also I have this this just before the rror message
`INFO: Building HSL`
`INFO: looking for /home/.../.julia/v0.5/HSL/deps/downloads/hsl_ma97-2.3.0.tar.gz`
`INFO: hsl_ma97 found`

I don't understand why it's not found since it's there.. 
Sam

Edit: If I manually go change the expected number in the build.jl I get this new error:
`LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency libhsl_ma97`
`while loading /home/.../.julia/v0.5/HSL/deps/build.jl, in expression starting on line 36`

**Comment by dpo** [comment]
The info message indicates that the archive was found. Unfortunately, the sha sum changes occasionally.

Are you on OSX or Linux? Can you tell if BLAS, LAPACK and METIS were installed?
BinDeps is notoriously difficult to debug, but you could try
```
using BinDeps
BinDeps.debug("HSL")
```

**Comment by Goysa2** [comment]
I am on Linux (Ubuntu 16.04). I have the metis-4.0.3 in my HSL/deps/src but I couldn't tell for BLAS or LAPACK. 

When I use BinDeps to debug I have: 
`LoadError: UndefVarError: bindeps_context not defined`
 `in macro expansion; at /home/.../.julia/v0.5/BinDeps/src/dependencies.jl:834 [inlined]`
 `in anonymous at ./<missing>:?`
 `in eval(::Module, ::Any) at ./boot.jl:234`
 `in eval(::Any) at ./boot.jl:233`
 `in include_from_node1(::String) at ./loading.jl:488`
 `in debug_context(::String) at /home/.../.julia/v0.5/BinDeps/src/debug.jl:54`
 `in debug(::Base.TTY, ::String) at /home/.../.julia/v0.5/BinDeps/src/debug.jl:59`
 `in debug(::String) at /home/.../.julia/v0.5/BinDeps/src/debug.jl:71`
`while loading /home/.../.julia/v0.5/HSL/deps/build.jl, in expression starting on line 36`

**Comment by dpo** [comment]
That last message seems unrelated. Does it work if you `apt-get install` (or whatever Ubuntu uses) `libblas-dev` and `liblapack-dev`?

**Comment by dpo** [comment]
I upgraded to HSL_MA97 2.4.0 so the sha sum is different now. I'm going to go ahead and close this. Please open a new issue if you're still experiencing problems.
