### ISSUE TITLE
Add automatic docs

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/HSL.jl#90]
Following [NLPModelsKnitro.jl](https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl) example:
- [ ] Add a boolean success/failure instead of crashing when doing `using HSL` https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/issues/98
- [ ] Apply the usual JSO process for the docs, with index/references/tutorial
- [ ] Add the tutorial to [JSOTutorials.jl](https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl)

**Comment by dpo** [comment]
Actually, there's already such a mechanism in place here. #91 should do it.
