### ISSUE TITLE
Change the factorization type without re-computing the symbolic analysis

### ISSUE THREAD

**Issue by geoffroyleconte** [JuliaSmoothOptimizers/HSL.jl#97]
Hi, I need to be able to convert a `Ma57{Float32}` to a `Ma57{Float64}` without having to compute the symbolic analysis again. Is there an easy way I could do this? The default constructor for the `Ma57` struct has been erased.

**Comment by dpo** [comment]
It would need some restructuring to separate the data structure for the symbolic analysis from that for the numerical factorization.
